app/__init__.py
#!/usr/bin/python3

from flask import Flask, render_template
from app.home import home
from app.stack import stack
from app.about import about

app = Flask(__name__)

@app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

app.register_blueprint(home)
app.register_blueprint(stack)
app.register_blueprint(about)

app/about/__init__.py
from flask import Blueprint

about = Blueprint('about', __name__)

from . import views

app/about/views.py
from . import about
from flask import render_template

@about.route('/about')
def aboutpage():
    return render_template('about.html')

app/home/__init__.py
#!/usr/bin/python3
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
#!/usr/bin/python3

from . import home
from flask import render_template

@home.route('/')
def homepage():
    return render_template('home.html')

app/stack/__init__.py
from flask import Blueprint

stack = Blueprint('stack', __name__)

from . import views

app/stack/views.py
from . import stack
from flask import render_template

@stack.route('/stack')
def stackpage():
    return render_template('stack.html')

app/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aura - About</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='navbar.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='slider.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='container-item.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="navbar">
        <a href="{{ url_for('home.homepage') }}" style="float: left;">Aura</a>
        <a href="" style="color:rgb(52, 32, 165);" title="Constuindo">Login Or Register</a>
    </div>
    <div class="slider">
        <img src="{{ url_for('static', filename='img/aura-wait.png')}}"/>    
        <h1 style="font-size: 24px;">A Aura chat é uma rede social para programadores...<br>Criada em 16/04/20 por <a href="https://github.com/freazesss">Gustavo Lins</a></h1>
    </div>
</body>
</html>

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aura - Home</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='navbar.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='container-item.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='responsive.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='slider.css')}}">
</head>
<body>
    <div class="navbar">
        <a href="{{ url_for('home.homepage') }}" style="float: left;">Aura</a>
        <a href="" style="color:rgb(52, 32, 165);">Login Or Register</a>
    </div>
    <div class="slider">
        <img src="{{ url_for('static', filename='img/aura-wait.png')}}"/>    
    </div>
    <div class="container">
        <div class="link">
            <h1>Devs</h1>
            <a href="https://github.com/aurachat">Open-Source</a>
            <a href="{{ url_for('stack.stackpage')}}">Stack</a>
        </div>
        <div class="link">
            <h1>Recursos</h1>
            <a href="">Termos</a>
        </div>
        <div class="link">
            <h1>Empresa</h1>
            <a href="{{ url_for('about.aboutpage')}}">Sobre</a>
        </div>
    </div>
</body>
</html>

app/templates/stack.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aura - Stack</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='navbar.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='slider.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='container-item.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="navbar">
        <a href="{{ url_for('home.homepage') }}" style="float: left;">Aura</a>
        <a href="" style="color:rgb(52, 32, 165);" title="Constuindo">Login Or Register</a>
    </div>
    <div class="slider">
        <h1>Python     Flask</h1>
    </div>
</body>
</html>